### ISSUE TITLE
Korean Hangul key 

### ISSUE THREAD

**Issue by Shaun289** [rustdesk/rustdesk#1583]
```
KeyPress event, serial 37, synthetic NO, window 0x4000001,
    root 0x774, subw 0x0, time 9995364, (2278,831), root:(2388,940),
    state 0x10, keycode 130 (keysym 0xff31, Hangul), same_screen YES,
    XKeysymToKeycode returns keycode: 108
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x4000001,
    root 0x774, subw 0x0, time 9995468, (2278,831), root:(2388,940),
    state 0x10, keycode 130 (keysym 0xff31, Hangul), same_screen YES,
    XKeysymToKeycode returns keycode: 108
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 38, synthetic NO, window 0x4000001,
    root 0x774, subw 0x0, time 9999036, (2278,831), root:(2388,940),
    state 0x10, keycode 108 (keysym 0xff31, Hangul), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x4000001,
    root 0x774, subw 0x0, time 9999132, (2278,831), root:(2388,940),
    state 0x10, keycode 108 (keysym 0xff31, Hangul), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
The log is xev capture for Hangul key.

My main PC is Ubuntu 20.04 and I'm using rustdesk to connect sub PC.
In korean keyboard, keycode 130 and 108 are Hangul key that is switching English/Korean.
But these key codes do not work.
It's really uncompatible for Korean.
Could you fix it? Or let me know the code to fix it myself please.

**Comment by rustdesk** [comment]
Could you try out nightly build? 
@asur4s

**Comment by asur4s** [comment]
https://github.com/rustdesk/rustdesk/pull/1032#issue-1315793222

Similar to this issue, but only the Windows side was fixed at the time. It seems that either Mac or Linux has this problem

**Comment by Shaun289** [comment]
I installed nightly version, but it didn't resolve the issue.
[rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb)

**Comment by Shaun289** [comment]
I installed nightly version Windows side.
When I entered some keyboard, the windows client was crashed and then disconnected.

**Comment by asur4s** [comment]
Just now, I found the cause of the Windows crash, the rust version on CI is different from the development environment, and some function behaviors have changed in the latest version.

**Comment by rustdesk** [comment]
@Shaun289 how does korean keyboard look like? Can you give us a picture, and which key is Hangul ?

**Comment by Shaun289** [comment]
https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:KB_South_Korea.svg
The image is the korean keyboard layout.
한/영 is Hangul key. You can find the key on the right side of the space bar.

https://en.wikipedia.org/wiki/Keyboard_layout#Dubeolsik
Dubeolsik is the standard of Hangul keyboard.

**Comment by rustdesk** [comment]
@Shaun289 could you test the newest nightly build again? nightly build on both side.

**Comment by Shaun289** [comment]
It's working! Really appreciate it!

**Comment by asur4s** [comment]
If the problem is solved, close the issue, thx @Shaun289
