### ISSUE TITLE
About RustDesk The master terminal cannot disconnect the controlled terminal

### ISSUE THREAD

**Issue by yujiahan2018** [rustdesk/rustdesk#327]
After the master terminal of RustDesk is connected to the controlled terminal, the exit can only be realized by the controlled terminal manually closing or the master terminal moves the mouse to the closed window, but the connection of the controlled terminal cannot be disconnected by shortcut keys. In many cases, the operation of the controlled terminal will be troubled

**Comment by rustdesk** [comment]
Close button on titlebar not work?

![image](https://user-images.githubusercontent.com/71636191/145437166-f75e9bc7-454c-47db-a5ae-6683aa1bdfed.png)

**Comment by fufesou** [comment]
![1639071642(1)](https://user-images.githubusercontent.com/13586388/145447782-37fedaf3-90d5-4086-bbb1-a4386079ee71.png)

These bugs happen on installed app.
The binary built on latest master branch works fine.

I'm not sure where it's fixed in code or install process causes something wrong.
I'll keep on tracking this problem.

**Comment by mr-gosh** [comment]
I have do admit that this behaviour is still present on my machine.
I can close the rust desktop client or push the "close connection" button and i am still connected.

**Comment by zepef** [comment]
Hello,

On my Windows PC I use the 3 fingers salute to close the local service instance. Not pretty but efficient !

**Comment by hueldoeu** [comment]
i can't click on disconnect with local computer on the remote computer during a rustdesk-session.
