### ISSUE TITLE
Android compatibility issues

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#3893]
### Bug Description

x

### How to Reproduce

x

### Expected Behavior

x

### Operating system(s) on local side and remote side

x

### RustDesk Version(s) on local side and remote side

x

### Screenshots

x

### Additional Context

x

**Comment by Unknown78** [comment]
Hi, I'm the one that issued https://github.com/rustdesk/rustdesk/issues/1729

There's no explanation of this thread that I could find.
What does this thread for?
What should I do?

Do I need to retest everything with the latest nightly version or what?

**Comment by uliscat** [comment]
Hello. Tested rustdesk w' android 10 / 11 / 12, using Logitech MX Keys Mini, Kensington Wireless, Samsers Foldable keyboards.
Absolutely nothing works. 
Pretty sad, but today we can state that **android** **bluetooth** keyboard support is completely **broken**. :-(

**Comment by fufesou** [comment]
@uliscat Hi, the physical keyboard issue should be fixed by PR #3956 . It was my fault to break the physical keyboard.

**Comment by fufesou** [comment]
Yes, the keyboard is fixed. Please confirm, thanks.

**Comment by 29039** [comment]
I think I have this keyboard bug as well, where can I get the nightly to test? The one on releases page is Oct 21, 2022, and bug still exists there

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by 29039** [comment]
> https://github.com/rustdesk/rustdesk/releases/tag/nightly

Thanks, got mixed up because I was looking at the date, when filing a bug it is hard to say *which* nightly is being referred to because nighties get overridden

**Comment by fufesou** [comment]
> language switch/keyboard layout switch does not work

@uliscat Thanks for your feedback.
But I can't reproduce your issue.

What shortcut do you use to switch language layout?
I use "Win + Space".
