### ISSUE TITLE
The colors look weird

### ISSUE THREAD

**Issue by jjqtony** [rustdesk/rustdesk#5368]
### Bug Description

When I connect to Win 11 with 4K resolution using rustdesk 1.2.1, the colors of the screen look weird.
When I connect to Win 10 with 4K resolution using rustdesk 1.2.1, the colors of the screen look OK.

### How to Reproduce

 connect to Win 11 with 4K resolution 

### Expected Behavior

the color should be same as local color

### Operating system(s) on local side and remote side

Windows 11 -> windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![ww](https://github.com/rustdesk/rustdesk/assets/20393479/dcf51335-6bc2-497a-9f17-388915c471c7)

**Comment by jjqtony** [comment]
I have fixed this problem. HDR should take the blame for this problem. When turn off HDR, the colors are normal.

**Comment by abelian424** [comment]
Remmina using RDP can connect to an HDR desktop just fine, so I'd say it's a shortcoming of the protocol that RustDesk uses. Not sure if this issue should be closed just because there's a workaround.

**Comment by maen693** [comment]
I still have the problem. The color seems weird.

![Image](https://github.com/user-attachments/assets/9eac18e7-0dfe-4c5d-b75c-4ee0c92b5c1d)

**Comment by squadjot** [comment]
Have the same problem, i think it may be a GPU thing

This is how it looks , it's too overexposed.
<img width="451" height="161" alt="Image" src="https://github.com/user-attachments/assets/f1fadc5d-9b3f-44d7-8d0d-bcfe60080e05" />

### The "funny thing" is.. 
To be able to show you how it looks, i have to open OBS recorder (showing my desktop), and take a screenshot of that instead of the "real" window.

If i take a screenshot the "normal" way in windows, the output looks normal. 
<img width="561" height="199" alt="Image" src="https://github.com/user-attachments/assets/78b96b99-7a0f-44f1-ab83-c77194731d62" />


And i have no HDR

<img width="859" height="109" alt="Image" src="https://github.com/user-attachments/assets/8361924f-978a-41d2-9885-88013080ed6c" />



And no apparent "colorboosting" from my NVDIA 4060ti

<img width="1332" height="1506" alt="Image" src="https://github.com/user-attachments/assets/0cacc890-166b-4677-8d58-37e0a97f177c" />

<img width="1228" height="477" alt="Image" src="https://github.com/user-attachments/assets/e7b70689-2802-47cd-9249-6ddda50f1204" />

**Comment by andmpel** [comment]
This should be reopened I feel

**Comment by kingwingfly** [comment]
I've developed a screen capture library for my company, and capturing from D3D11 is correct with no HDR problem. But on macOS, here's `SCStreamConfigurationPreset::CaptureHDRStreamCanonicalDisplay` which will lead to similar problem. However, I thought it's not Windows' fault here, maybe re-writing this crate https://crates.io/crates/windows-capture can fix.

**Comment by HRussellZFAC023** [comment]
add a shortcut on your desktop that does win + alt +B. Pressing win + alt + B twice always fixes the issue for me

**Comment by dixtdf** [comment]
While using HDMI brightness adjustment software recently, I accidentally discovered that HDR brightness can be adjusted. After adjusting the brightness, the RustDesk view appears much more normal and no longer suffers from overexposure. I haven’t tried the DP interface yet, but it might also work.
https://github.com/xanderfrangos/twinkle-tray

<img width="516" height="270" alt="image" src="https://github.com/user-attachments/assets/69fe6117-eb60-4b5e-9b72-e749e1af0537" />

https://github.com/rustdesk/rustdesk/discussions/7652#discussioncomment-17101284
