### ISSUE TITLE
RustDesk 1.1.9 64-bit cannot be installed on Windows 10 Professionnel (21H2)

### ISSUE THREAD

**Issue by Nemrissme** [rustdesk/rustdesk#677]
Hello,

When I try to install RustDesk 1.1.9 64-bit on a computer with Windows 10 Professional (21H2), I get the following error message :

![Capture](https://user-images.githubusercontent.com/106674727/171418631-fd8746ea-8518-482a-8dcd-56c49a9da24b.jpg)

I can't figure out what the problem is.

Thanks in advance to those who can help me.

Have a nice day.

**Comment by Nemrissme** [comment]
Yes, sorry for the oversight.

This file does not contain an associated application to perform this action. Install an application or, if you have already done so, create an association on the Default Application Settings page.

When I go to the C:\Users\113 AppData\Local\Temp\ folder, I can't find the file "RustDesk_0x1e9df3192d0.cmd"

**Comment by Nemrissme** [comment]
If I ignore the error, the program does not install. Therefore there is no RustDesk folder in C:Program Files.

**Comment by Nemrissme** [comment]
With this file it works and I have a RustDesk folder in C:Program Files.

**Comment by rustdesk** [comment]
Try out https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip

**Comment by chmis8000** [comment]
The problem is solved, the rustdesk-1.1.9-windows_x32-portable.zip I downloaded is installed on the win2008R2 system, and the same error is the same as the landlord. There is no problem with the latest 64-bit version.

**Comment by Nemrissme** [comment]
It still doesn't work for me even with the last link, I always get an error message when I try to install it.

![Capture](https://user-images.githubusercontent.com/106674727/171624427-3bfaf15d-3fa6-43f4-b0fb-f644e31676d7.PNG)

"There is no script engine for the .vbs file extension"

**Comment by rustdesk** [comment]
Then I have no work around also. Your Windows looks so diffrent.

**Comment by Nemrissme** [comment]
No worries, I will use it in a portable way. Thank you for your availability and responsiveness.

**Comment by rustdesk** [comment]
Wait, let me have another try later.

**Comment by rustdesk** [comment]
tyr out this one https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe?

**Comment by Nemrissme** [comment]
I have no more error messages with this latest version and the RustDesk folder is well created in the C:Program Files folder.

I just have the shortcut on the desktop which is not created but this point is not important.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/11
